#!/usr/bin/env python3
"""Prove that constraints.txt is exactly the set pip resolves for the image, without building it.

The image installs vLLM's requirements with `pip install -c constraints.txt`. That only makes the
build reproducible if the file is complete (every package pip pulls in is pinned) and consistent
(every pin satisfies vLLM's ranges, so the install does not fail after hours of compiling). Both
break silently: a Renovate bump can leave a vLLM range (`fastapi < 0.137.0`), a new release of a
package can add a dependency, and a vLLM bump changes the requirement set as a whole.

This replays the image's install in a throwaway venv with `pip install --dry-run`:
  * vLLM's requirements at the pinned tag (requirements/rocm.txt with its -r includes, the torch
    lines stripped the way the builder's `use_existing_torch.py` strips them),
  * plus what the Dockerfile adds by hand (transformers at its ARG, pillow, pybind11),
  * against stub installs of the packages the builder compiles (torch, triton, torchvision,
    amd-aiter), so nothing resolves those from PyPI. The stubs declare the dependencies of the
    same version's PyPI wheel minus the CUDA ones -- which is what the ROCm builds declare --
    because pip does resolve an installed package's dependencies once something needs it,
and compares the resolution with constraints.txt, both ways.

It also derives Renovate's limits from the same resolution. Renovate knows each package on its
own; it does not know that numba 0.65.0 needs llvmlite < 0.48 or that grpcio-reflection needs
protobuf < 7, so its weekly group PR would fail here every week. Every pinned package that some
other installed package (or vLLM) pins exactly (`==`) gets `enabled: false` in renovate.json, every
upper bound or exclusion (`<`, `<=`, `!=`, `~=`) becomes `allowedVersions`. These rules are
generated (their description starts with GENERATED) and checked like the pins.

    python3 ci/check_constraints.py            # check (CI); exit 1 on any difference
    python3 ci/check_constraints.py --caps     # rewrite only the generated renovate.json rules
    python3 ci/check_constraints.py --update   # rewrite the pins from a fresh resolution + the rules

    python3 ci/check_constraints.py --repair   # make a Renovate PR's pins consistent (CI does it)

--update is for a vLLM bump (or a pin that no longer resolves): it resolves without the old pins,
i.e. to the newest versions vLLM's ranges allow, and keeps the header of the file.

--repair is for a Renovate PR that fails the check. Renovate looks each package up on its own, so a
group PR can hold versions that do not fit together (pydantic-core ahead of what pydantic pins
exactly, httpx2 without the httpcore2 it pins, boto3 without its botocore). Only the pins the PR
changed against --base (default origin/main) are loosened, to `>=base,<=proposed`; everything else
stays exact, and pip picks the newest set that resolves: consistent, never newer than Renovate
proposed, never older than main, and unchanged wherever the proposal already fits. If that still
does not resolve, every pin is loosened the same way (`>=base` where main has it). The
`constraints` job in ci.yml runs it on renovate/* branches and pushes the result.

Needs the image's interpreter (python 3.12) on linux x86_64, like the GitHub runner: pip evaluates
environment markers for the running platform.
"""
import argparse
import json
import re
import subprocess
import sys
import tempfile
import urllib.request
import venv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "ci"))
from read_pins import read_pins  # noqa: E402

CONSTRAINTS = ROOT / "constraints.txt"
RENOVATE = ROOT / "renovate.json"
GENERATED = "GENERATED by ci/check_constraints.py"
# operators that stop Renovate from proposing a version; a plain lower bound never does
LIMITING = ("<", "<=", "!=", "~=", "==", "===")
RAW = "https://raw.githubusercontent.com/vllm-project/vllm/v{ver}/{path}"
# Installed by the Dockerfile before the pinned resolution, not from PyPI.
BOOTSTRAP = ("pip", "setuptools", "wheel")


def canon(name):
    return re.sub(r"[-_.]+", "-", name).lower()


def fetch(ver, path):
    with urllib.request.urlopen(RAW.format(ver=ver, path=path), timeout=60) as r:
        return r.read().decode()


def vllm_requirements(ver):
    """requirements/rocm.txt at the tag, -r includes inlined, torch lines stripped."""
    out, seen = [], set()

    def walk(path):
        if path in seen:
            return
        seen.add(path)
        for line in fetch(ver, path).splitlines():
            s = line.split("#", 1)[0].strip()
            if s.startswith("-r "):
                walk(str(Path(path).parent / s[3:].strip()))
            elif s and "torch" not in s.lower():  # use_existing_torch.py (no --prefix)
                out.append(s)

    walk("requirements/rocm.txt")
    return out


def read_constraints():
    header, pins = [], {}
    for line in CONSTRAINTS.read_text().splitlines():
        s = line.strip()
        if "==" in s and not s.startswith("#"):
            name, ver = s.split("==", 1)
            pins[canon(name)] = (name, ver.strip())
        elif not pins:
            header.append(line)
    return header, pins


def pypi_requires(name, version):
    """Requires-Dist of the PyPI release, without the CUDA wheels and the stubbed siblings."""
    url = f"https://pypi.org/pypi/{name}/{version}/json"
    with urllib.request.urlopen(url, timeout=60) as r:
        reqs = json.load(r)["info"]["requires_dist"] or []
    drop = re.compile(r"^(nvidia-|cuda-|torch\b|triton\b|torchvision\b)", re.I)
    return [q for q in reqs if not drop.match(q)]


def stub(site, name, version, requires=()):
    d = site / f"{name.replace('-', '_')}-{version}.dist-info"
    d.mkdir()
    meta = f"Metadata-Version: 2.1\nName: {name}\nVersion: {version}\n"
    meta += "".join(f"Requires-Dist: {q}\n" for q in requires)
    (d / "METADATA").write_text(meta)
    (d / "INSTALLER").write_text("stub\n")
    (d / "RECORD").write_text("")


def pip(py, *args):
    return subprocess.run([py, "-m", "pip", "--disable-pip-version-check", *args],
                          capture_output=True, text=True)


def resolve(pins_file, reqs, pins=None):
    """Resolve in a throwaway venv -> (resolved {canon: (name, version)}, generated Renovate rules).

    `pins` are the names the rules are for (default: the resolution itself)."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        venv.EnvBuilder(with_pip=True).create(tmp / "venv")
        py = str(tmp / "venv" / "bin" / "python")
        site = next((tmp / "venv" / "lib").glob("python3*/site-packages"))
        p = read_pins()
        for name, arg in (("torch", "TORCH_VERSION"), ("triton", "TRITON_VERSION"),
                          ("torchvision", "TORCHVISION_VERSION")):
            stub(site, name, f"{p[arg]}+rocm", pypi_requires(name, p[arg]))
        # installed --no-deps and nothing in vLLM's requirements pulls it in: no dependencies
        stub(site, "amd-aiter", p["AITER_VERSION"])
        cons = ["-c", str(pins_file)] if pins_file else []

        # the Dockerfile's first pip call
        r = pip(py, "install", "-U", *BOOTSTRAP, *cons)
        if r.returncode:
            raise SystemExit(f"FAIL: bootstrap install\n{r.stdout[-2000:]}{r.stderr[-3000:]}")
        (tmp / "reqs.txt").write_text("\n".join(reqs) + "\n")
        r = pip(py, "install", "--dry-run", "--report", str(tmp / "report.json"),
                *cons, "-r", str(tmp / "reqs.txt"),
                f"transformers=={p['TRANSFORMERS_VERSION']}", "pillow", "pybind11")
        if r.returncode:
            # pip names the culprit ("The conflict is caused by: ...") on stdout, the verdict on stderr
            why = r.stdout[r.stdout.find("The conflict is caused by"):] if "conflict is caused" in r.stdout else ""
            raise SystemExit("FAIL: pip cannot resolve vLLM's requirements against constraints.txt "
                             "(a pin outside a range?):\n" + why[-4000:] + r.stderr[-2000:])
        installs = json.loads((tmp / "report.json").read_text())["install"]
        resolved = {canon(i["metadata"]["name"]): (i["metadata"]["name"], i["metadata"]["version"])
                    for i in installs}
        # who asks for what: (requirer, requirement string), for the Renovate limits
        edges = [("vllm", q) for q in reqs]
        edges += [(i["metadata"]["name"], q) for i in installs
                  for q in i["metadata"].get("requires_dist") or []]
        # everything already installed: the bootstrap (pip, setuptools, wheel and their
        # dependencies) and the stubs, with their own requirements
        stubs = {"torch", "triton", "torchvision", "amd-aiter"}
        inspect = json.loads(pip(py, "inspect").stdout)["installed"]
        for i in inspect:
            m = i["metadata"]
            edges += [(m["name"], q) for q in m.get("requires_dist") or []]
            if canon(m["name"]) not in stubs:
                resolved[canon(m["name"])] = (m["name"], m["version"])
        resolved.pop("transformers", None)  # pinned by its Dockerfile ARG
        # the venv's pip carries packaging (for markers and specifiers); the host python may not
        sys.path.insert(0, str(site))
        try:
            rules = renovate_caps(pins if pins is not None else resolved, edges)
        finally:
            sys.path.remove(str(site))
        return resolved, rules


def renovate_caps(pins, edges):
    """The generated renovate.json rules: what the rest of the resolution allows for each pin."""
    from pip._vendor.packaging.requirements import Requirement

    parsed = [(who, Requirement(q)) for who, q in edges]
    # extras that something asks for, so `extra == "..."` requirements are evaluated correctly
    extras = {}
    for _ in range(2):
        for who, r in parsed:
            for e in list(extras.get(canon(who), {""})):
                if r.marker is None or r.marker.evaluate({"extra": e}):
                    extras.setdefault(canon(r.name), {""}).update(r.extras)
    limits = {}
    for who, r in parsed:
        if canon(r.name) not in pins or canon(who) == canon(r.name):
            continue
        if r.marker is not None and not any(r.marker.evaluate({"extra": e})
                                            for e in extras.get(canon(who), {""})):
            continue
        specs = [str(sp) for sp in r.specifier if sp.operator in LIMITING]
        if specs:
            limits.setdefault(canon(r.name), {}).setdefault(",".join(sorted(specs)), set()).add(who)
    rules = []
    for k in sorted(limits):
        name = pins[k][0]
        spec = ",".join(sorted({sp for s in limits[k] for sp in s.split(",")}))
        who = ", ".join(sorted({w for ws in limits[k].values() for w in ws}, key=str.lower))
        rule = {"description": f"{GENERATED}: {name} {spec} (required by {who})",
                # Renovate matches the normalized PyPI name (pydantic_core -> pydantic-core)
                "matchManagers": ["pip_requirements"], "matchPackageNames": [k]}
        exact = any(sp.startswith("==") and not sp.endswith("*") or sp.startswith("===")
                    for sp in spec.split(","))
        if exact:
            rule["enabled"] = False
        else:
            rule["allowedVersions"] = spec
        rules.append(rule)
    return rules


def sync_caps(rules, write):
    """Compare (or replace) the GENERATED packageRules of renovate.json; True when current."""
    cfg = json.loads(RENOVATE.read_text())
    keep = [r for r in cfg["packageRules"] if not r.get("description", "").startswith(GENERATED)]
    current = [r for r in cfg["packageRules"] if r.get("description", "").startswith(GENERATED)]
    if current == rules:
        return True
    if write:
        cfg["packageRules"] = keep + rules
        RENOVATE.write_text(json.dumps(cfg, indent=2) + "\n")
    return False


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--update", action="store_true", help="rewrite constraints.txt and the rules")
    ap.add_argument("--caps", action="store_true", help="rewrite only the generated renovate.json rules")
    ap.add_argument("--repair", action="store_true",
                    help="re-resolve the pins changed against --base as ranges, rewrite file + rules")
    ap.add_argument("--base", default="origin/main",
                    help="--repair: git ref (or file) holding the constraints.txt the PR started from")
    args = ap.parse_args(argv)
    if sys.version_info[:2] != (3, 12):
        print(f"WARNING: python {sys.version.split()[0]}, the image runs 3.12 -- markers may differ")

    ver = read_pins()["VLLM_VERSION"]
    reqs = vllm_requirements(ver)
    header, pins = read_constraints()
    print(f"vLLM {ver}: {len(reqs)} requirements; constraints.txt: {len(pins)} pins")

    if args.update:
        resolved, rules = resolve(None, reqs)
        lines = header + [f"{n}=={v}" for n, v in sorted(resolved.values(), key=lambda x: canon(x[0]))]
        CONSTRAINTS.write_text("\n".join(lines) + "\n")
        changed = {k for k in resolved.keys() | pins.keys() if resolved.get(k, (0, 0))[1] != pins.get(k, (0, 0))[1]}
        print(f"constraints.txt rewritten: {len(resolved)} pins, {len(changed)} changed")
        sync_caps(rules, write=True)
        print("renovate.json: generated rules rewritten")
        return 0

    if args.repair:
        if Path(args.base).is_file():
            base_text = Path(args.base).read_text()
        else:
            base_text = subprocess.run(["git", "show", f"{args.base}:constraints.txt"], cwd=ROOT,
                                       check=True, capture_output=True, text=True).stdout
        base = {canon(n): v.strip() for n, v in
                (ln.strip().split("==", 1) for ln in base_text.splitlines()
                 if "==" in ln and not ln.lstrip().startswith("#"))}

        def ranged(k, name, v):
            return f"{name}>={base[k]},<={v}" if k in base else f"{name}<={v}"

        changed = {k for k, (n, v) in pins.items() if base.get(k) != v}
        attempts = (("changed pins loosened", lambda k, n, v: ranged(k, n, v) if k in changed else f"{n}=={v}"),
                    ("all pins loosened", ranged))
        for label, line in attempts:
            with tempfile.NamedTemporaryFile("w", suffix=".txt") as caps:
                caps.write("".join(line(k, n, v) + "\n" for k, (n, v) in pins.items()))
                caps.flush()
                try:
                    resolved, rules = resolve(caps.name, reqs)
                    print(f"repair: resolved with {label} ({len(changed)} changed against {args.base})")
                    break
                except SystemExit as e:
                    print(f"repair: {label} does not resolve: {str(e)[:300]}")
        else:
            return 1
        lines = header + [f"{n}=={v}" for n, v in sorted(resolved.values(), key=lambda x: canon(x[0]))]
        CONSTRAINTS.write_text("\n".join(lines) + "\n")
        sync_caps(rules, write=True)
        for k in sorted(pins.keys() | resolved.keys()):
            old, new = pins.get(k, ("", "-"))[1], resolved.get(k, ("", "-"))[1]
            if old != new:
                print(f"  {(pins.get(k) or resolved.get(k))[0]}: proposed {old} -> {new}")
        print(f"constraints.txt repaired: {len(resolved)} pins; renovate.json rules regenerated")
        return 0

    resolved, rules = resolve(CONSTRAINTS, reqs, pins)
    if args.caps:
        print("renovate.json:", "unchanged" if sync_caps(rules, write=True) else "generated rules rewritten",
              f"({len(rules)} rules)")
        return 0
    missing = sorted(set(resolved) - set(pins))
    stale = sorted(set(pins) - set(resolved))
    for k in missing:
        n, v = resolved[k]
        print(f"::error file=constraints.txt::{n}=={v} is installed but not pinned -- add the line")
    for k in stale:
        n, v = pins[k]
        print(f"::error file=constraints.txt::{n}=={v} is pinned but nothing installs it any more -- drop the line")
    caps_ok = sync_caps(rules, write=False)
    if not caps_ok:
        print(f"::error file=renovate.json::the {GENERATED} rules are out of date -- "
              "run python3 ci/check_constraints.py --caps")
    if missing or stale or not caps_ok:
        print("FAIL (python3 ci/check_constraints.py --update re-resolves the whole file)")
        return 1
    print(f"constraints OK: {len(resolved)} packages, all pinned, none stale, all within vLLM's ranges; "
          f"{len(rules)} generated Renovate rules current")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
